name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Create reports directory if it doesn't exist
        run: mkdir -p reports
      
      - name: Move HTML files to reports directory (if in root)
        run: |
          for file in *.html; do
            if [[ "$file" != "index.html" && "$file" != "github_pages_index.html" && -f "$file" ]]; then
              mv "$file" reports/ || true
            fi
          done
      
      - name: Copy index.html to root if needed
        run: |
          if [ -f "github_pages_index.html" ]; then
            cp github_pages_index.html index.html
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2